### ISSUE TITLE
Tabs always seem to take 100% of the width

### ISSUE THREAD

**Issue by mpetzold** [vaadin/vaadin-tabs-flow#112] opened 2019-07-03 10:19 UTC
I would like to place a button next to the left side of the tabs, but not belonging to the tabs. Basic approach would be to take a HorizontalLayout, add a Button and add Tabs. However, this does not work because Tabs always take 100% of the width. It is also not possible to make changes to the "scroll" div using the Java API.

Example:
```
private class Navigation extends HorizontalLayout {
	public Navigation() {
		this.setWidthFull();
		
		this.add(new Button("Test", click -> { ... }));
		
		Tab tab1 = new Tab("Tab one");
		Tab tab2 = new Tab("Tab two");
		Tab tab3 = new Tab("Tab three");
		this.add(new Tabs(tab1, tab2, tab3));
	}
}
```

Should be:

Button Tabs 

Is:

Button
Tabs

Browser version: Chrome 75.0.3770.100
Vaadin version: 14.0.0.rc2
Java version: 1.8
OS version: Debian 9

**Comment by mpetzold** [comment] 2019-07-04 08:22
Any changes to the implementation? Today it works! Maybe fixed?

**Comment by web-padawan** [comment] 2020-07-24 10:40
I could not reproduce this issue. Not sure why it happened, there hasn't been any changes that could cause it. Closing.

**Closed by web-padawan** 2020-07-24 10:40 UTC
